version: '3.8'

services:
  db:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    networks:
      - net
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: todo
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - datavolume/data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongoose:27017/todo --quiet
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 50

  server:
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    container_name: server
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy 
    ports:
      - 5000:5000

  client:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    container_name: client
    networks:
      - net
    ports:
      - 3000:3000 
    depends_on:
      server:
        condition: service_started  
        
volumes:
  datavolume:

networks:
  net:
    driver: bridge
